[package]
name = "cnet-homework-by-rust"
version = "0.1.0"
authors = ["ahabhgk <ahabhgk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
chrono = "0.4.19"
base64 = "0.13.0"
